# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np

x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]).reshape(2,5)
x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array ([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array ([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_array = np.array([arr1,arr2,arr3])


arr4 = np.concatenate(array_of_array)
arr4

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::


array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [ ]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

print ("Before Converstion Result :")
print ("\n", a)

print ("after Convert higher into one dimension")

b = a.flatten()
b

Before Converstion Result :

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
after Convert higher into one dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

a

b = a.reshape(1,5,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [ ]:
a = np.arange(25).reshape(5,5)
b = np.sqrt(a)
b

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
import numpy as np

a = np.arange(30).reshape(5,6)
b = np.mean(a)
print ("The mean of 5x6 arrays is :",b)

The mean of 5x6 arrays is : 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
a = np.arange(30).reshape(5,6)
b = np.std(a)
print ("The deviation of 5x6 arrays is :",b)

The mean of 5x6 arrays is : 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [ ]:
a = np.arange(30).reshape(5,6)
b = np.median(a)
print ("The median of 5x6 arrays is :",b)

The median of 5x6 arrays is : 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
a = np.arange(30).reshape(5,6)
b = np.transpose(a)
print (b)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
a = np.arange(16).reshape(4,4)
print (a)
b = np.diagonal(a)
print (b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]


## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
a = np.arange(16).reshape(4,4)
print (a)
b = np.linalg.det(a)
print (b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.percentile(a,5)
c = np.percentile(a,95)
print (b)
print (c)

0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [ ]:
a = np.array([[[1,2,3,0], [0,0,3,4], [1,5,0,0]]])

print (a)

b = np.where(a<=0, "Null Values", a)
b



[[[1 2 3 0]
  [0 0 3 4]
  [1 5 0 0]]]


array([[['1', '2', '3', 'Null Values'],
        ['Null Values', 'Null Values', '3', '4'],
        ['1', '5', 'Null Values', 'Null Values']]], dtype='<U21')